# Generated by Django 3.2.6 on 2021-08-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special status', 'Can read all books')]},
        ),
    ]
